### ISSUE TITLE
How to Reduce the Bottom and Top Margin 

### ISSUE THREAD

**Issue by akshaylamba** [InvalidExcepti0n/IEBubbleView#1]
The Bottom and Top margin is Not required ...How to Remove it... 

When We do the Bubble to wrap_content height and width...

**Comment by ddB0515** [comment]
sorry for late response...didn't got mail for new issue...need to fix it
will solve this tonight as I know where is issue convertDpToPixel have some hardcoded values so if you wanna play with it untilll I update it
Thanks for report

**Comment by akshaylamba** [comment]
Pls let me know when the update is done...

**Comment by ddB0515** [comment]
I have updated it, please try if all works and let me know if is working for you
If working please close issue and I will create new release

**Comment by ddB0515** [comment]
closing due no response (will make release as I tested on mine phone)
